package publish

import (
	"html/template"
)

// indexTmpl is rendered to hn/index.html. One row per date, with columns
// for the readable HTML digest and the downloadable EPUB.
var indexTmpl = template.Must(template.New("index").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Hacker News Digests</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#0645ad">
<link rel="manifest" href="manifest.json">
<link rel="apple-touch-icon" href="favicon.ico">
<style>
 body{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;max-width:52rem;margin:2rem auto;padding:0 1rem;color:#222;background:#fafafa;line-height:1.5}
 h1{font-size:1.4rem;margin:0 0 0.25rem}
 p.sub{color:#666;margin:0 0 1.5rem}
 .actions{margin:0 0 1.5rem}
 .actions a{display:inline-block;padding:0.3rem 0.7rem;border:1px solid #ddd;border-radius:4px;color:#0645ad;text-decoration:none;background:#fff}
 .actions a:hover{background:#f0f0f0}
 ul{list-style:none;padding:0;margin:0}
 li{padding:0.5rem 0;border-bottom:1px solid #eee;display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap;align-items:baseline}
 li .date{font-weight:600;min-width:9em}
 li .formats{display:flex;gap:0.8rem;flex-wrap:wrap}
 li .formats a{color:#0645ad;text-decoration:none}
 li .formats a:hover{text-decoration:underline}
 .size{color:#888;font-size:0.85em;margin-left:0.25em}
 .na{color:#bbb;font-size:0.9em}
 footer{margin-top:2rem;color:#888;font-size:0.85em}
 footer a{color:#666}
</style>
</head>
<body>
<h1>Hacker News Digests</h1>
<p class="sub">Plain-language digests of the HN top stories, generated by <a href="https://github.com/denislee/hn-parser">hn-parser</a>. Newest first. HTML to read in the browser, EPUB to load on an e-reader, MD for plain text.</p>
<p class="actions"><a href="./" title="Refresh this page">↻ Reload</a></p>
<ul>
{{- range .Entries }}
  <li>
    <span class="date">{{ .Date }}</span>
    <span class="formats">
      {{- if .HTML.Name }}<a href="{{ .HTML.Name }}">HTML</a><span class="size">{{ .HTML.Size }}</span>{{ else }}<span class="na">HTML —</span>{{ end }}
      {{ if .EPUB.Name }}<a href="{{ .EPUB.Name }}">EPUB</a><span class="size">{{ .EPUB.Size }}</span>{{ else }}<span class="na">EPUB —</span>{{ end }}
      {{ if .MD.Name }}<a href="{{ .MD.Name }}">MD</a><span class="size">{{ .MD.Size }}</span>{{ else }}<span class="na">MD —</span>{{ end }}
      {{ if .SimplifiedMD.Name }}<a href="{{ .SimplifiedMD.Name }}">Simplified MD</a><span class="size">{{ .SimplifiedMD.Size }}</span>{{ else }}<span class="na">Simplified MD —</span>{{ end }}
    </span>
  </li>
{{- else }}
  <li>No digests yet.</li>
{{- end }}
</ul>
<footer>Last updated {{ .Updated }}.</footer>
<script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('sw.js').then(reg => {
        console.log('SW registered:', reg);
      }).catch(err => {
        console.log('SW registration failed:', err);
      });
    });
  }
</script>
</body>
</html>
`))

type indexData struct {
	Entries []indexEntry
	Updated string
}

type indexEntry struct {
	Date         string
	HTML         indexFile
	EPUB         indexFile
	MD           indexFile
	SimplifiedMD indexFile
}

type indexFile struct {
	Name string
	Size string
}
